CREATE DATABASE yeticave_212155
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;
USE yeticave_212155;

CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL UNIQUE,
  class VARCHAR(128) NOT NULL UNIQUE
);
CREATE TABLE lots (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(128) NOT NULL,
  description TEXT NOT NULL,
  img VARCHAR(128) NOT NULL,
  price_initial INT NOT NULL,
  data_end TIMESTAMP NOT NULL,
  step_rate INT NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  cat_id INT UNSIGNED NOT NULL,
  user_winner_id INT UNSIGNED,
  FOREIGN KEY (user_id) REFERENCES user(user_id),
  FOREIGN KEY (cat_id) REFERENCES categories(cat_id),
  FOREIGN KEY (user_winner_id) REFERENCES user(user_winner_id)
);
CREATE TABLE rate (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  price_user INT NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  lot_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user(user_id),
  FOREIGN KEY (lot_id) REFERENCES lots(lot_id)
);
CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_name VARCHAR(128) NOT NULL,
  email VARCHAR(128) NOT NULL UNIQUE,
  password VARCHAR(64) NOT NULL,
  avatar VARCHAR(128),
  contact VARCHAR(256) NOT NULL
);