CREATE DATABASE yeticave
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;
USE yeticave;

CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name CHAR(128) NOT NULL UNIQUE,
  class CHAR(128) NOT NULL UNIQUE
);
CREATE TABLE lots (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name CHAR(128) NOT NULL UNIQUE,
  description CHAR(128) NOT NULL UNIQUE,
  img CHAR(128) NOT NULL UNIQUE,
  price_initial INT NOT NULL UNIQUE,
  data_end TIMESTAMP NOT NULL,
  step_rate INT NOT NULL UNIQUE,
  category CHAR(64) NOT NULL,
  user_id INT UNSIGNED NOT NULL
);
CREATE TABLE rate (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  price_initial INT NOT NULL UNIQUE,
  user_id INT UNSIGNED NOT NULL,
  lot_id INT UNSIGNED NOT NULL
);
CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  date_creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  email INT NOT NULL UNIQUE,
  password CHAR(64) NOT NULL,
  avatar CHAR(128) NOT NULL UNIQUE,
  contact CHAR(128) NOT NULL UNIQUE,
  lot_id INT UNSIGNED NOT NULL,
  rate_id  INT UNSIGNED NOT NULL
);
CREATE UNIQUE INDEX с_name ON categories(name);
CREATE UNIQUE INDEX с_email ON user(email);
CREATE UNIQUE INDEX с_user ON user(user_id);
CREATE INDEX с_contact ON user(contact);
CREATE INDEX с_lot ON rate(lot_id);